version: "3"



services:

  nodeosd:
    hostname: nodeosd
    image: sagansoftware/eos:v1.1.0
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    volumes:
      - ./docker/build_contracts.sh:/build_contracts.sh:ro
      - ./contract:/contracts/eosstrawpoll
      - ./docker/config.ini:/eos/build/data-dir/config.ini:ro

  keosd:
    hostname: keosd
    image: sagansoftware/eos:v1.1.0
    entrypoint: keosd
    command: >
      --wallet-dir /eos/build/data-dir
      --http-server-address=127.0.0.1:8900
      --http-alias=keosd:8900
      --http-alias=localhost:8900
    ports:
      - 8900:8900
    expose:
      - "8900"
    links:
      - nodeosd