version: "3"

services:

  nodeosd:
    hostname: nodeosd
    image: sagansoftware/eos:v1.1.3
    command: >
      --data-dir /eos/build/data-dir
      --config-dir /eos/build/data-dir
      --enable-stale-production
      --http-alias=nodeosd:8888
      --http-alias=127.0.0.1:8888
      --http-alias=localhost:8888
      --http-alias=nodeosd:8889
      --http-alias=127.0.0.1:8889
      --http-alias=localhost:8889
    ports:
      - 8888:8888
      - 8889:8889
      - 9876:9876
    expose:
      - "8888"
      - "8889"
    volumes:
      - ./:/contract:ro
      - ./build:/build
      - ./docker/config.ini:/eos/build/data-dir/config.ini:ro
      - ./docker/cert.pem:/eos/cert.pem:ro
      - ./docker/key.pem:/eos/key.pem:ro
      # - nodeos-data-volume:/eos/build/data-dir

  keosd:
    hostname: keosd
    image: sagansoftware/eos:v1.1.3
    entrypoint: keosd
    command: >
      --wallet-dir /eos/build/data-dir
      --http-server-address=127.0.0.1:8900
      --http-alias=keosd:8900
      --http-alias=localhost:8900
    ports:
      - 8900:8900
    expose:
      - "8900"
    links:
      - nodeosd
    volumes:
      - ./:/contract:ro
      - ./build:/build

  tnodeosd:
    hostname: tnodeosd
    image: sagansoftware/telos:stage2.0
    entrypoint: nodeos
    command: >
      --data-dir /telos/build/data-dir
      --config-dir /telos/build/data-dir
      --genesis-timestamp 2018-09-02T12:00:00.000
      --enable-stale-production
      --http-alias=tnodeosd:8888
      --http-alias=tnodeosd:8889
      --http-alias=tnodeosd:10888
      --http-alias=tnodeosd:10889
      --http-alias=127.0.0.1:10888
      --http-alias=127.0.0.1:10889
      --http-alias=localhost:10888
      --http-alias=localhost:10889
    ports:
      - 10888:8888
      - 10889:8889
      - 10876:9876
    expose:
      - "8888"
      - "8889"
    volumes:
      - ./:/contract:ro
      - ./build:/build
      - ./docker/config_telos.ini:/telos/build/data-dir/config.ini:ro
      - ./docker/cert.pem:/telos/cert.pem:ro
      - ./docker/key.pem:/telos/key.pem:ro

  tkeosd:
    hostname: tkeosd
    image: sagansoftware/telos:stage2.0
    entrypoint: tkeosd
    command: >
      --wallet-dir /telos/build/data-dir
      --http-server-address=127.0.0.1:10900
      --http-alias=tkeosd:10900
      --http-alias=localhost:10900
    ports:
      - 10900:10900
    expose:
      - "10900"
    volumes:
      - ./:/contract:ro
      - ./build:/build
    links:
      - tnodeosd