version: "3"

services:

  nodeosd:
    hostname: nodeosd
    image: sagansoftware/eos:v1.1.3
    command: >
      --data-dir /eos/build/data-dir
      --config-dir /eos/build/data-dir
      --enable-stale-production
      --http-alias=nodeosd:8888
      --http-alias=127.0.0.1:8888
      --http-alias=localhost:8888
      --http-alias=nodeosd:8889
      --http-alias=127.0.0.1:8889
      --http-alias=localhost:8889
    ports:
      - 8888:8888
      - 8889:8889
      - 9876:9876
    expose:
      - "8888"
      - "8889"
    volumes:
      - ./:/contract:ro
      - ./build:/build
      - ./docker/config.ini:/eos/build/data-dir/config.ini:ro
      - ./docker/cert.pem:/eos/cert.pem:ro
      - ./docker/key.pem:/eos/key.pem:ro
      # - nodeos-data-volume:/eos/build/data-dir

  keosd:
    hostname: keosd
    image: sagansoftware/eos:v1.1.3
    entrypoint: keosd
    command: >
      --wallet-dir /eos/build/data-dir
      --http-server-address=127.0.0.1:8900
      --http-alias=keosd:8900
      --http-alias=localhost:8900
    ports:
      - 8900:8900
    expose:
      - "8900"
    links:
      - nodeosd
    # volumes:
    #   - keosd-data-volume:/eos/build/data-dir